# docker build . -t publicawesome/golang:1.21.3-devtooling -f docker/Dockerfile.go-devtools
FROM golang:1.21.12
RUN apt-get update && \
  apt-get install -y cmake && \
  apt-get -y clean && \
  rm -rf /var/lib/apt/lists/*
